### ISSUE TITLE
Traefik-route-k8s renders rules without `stripPrefix` middleware

### ISSUE THREAD

**Issue by natalian98** [PietroPasotti/traefik-route-k8s-operator#40]
### Bug Description

The traefik-route-k8s doesn't generate rules with the `stripPrefix` middleware, while the "ingress-per-app" does so.
Is this intentional? Is that middleware not needed with `ingress-per-unit`?

An example rule rendered by
- route charm:
```
http:
  routers:
    juju-prometheus-k8s-0-test-router:
      entryPoints:
      - web
      rule: Host(`prometheus-k8s-operator-0.prometheus-k8s-operator-endpoints.test.svc.cluster.local`)
      service: juju-prometheus-k8s-0-test-service
    juju-prometheus-k8s-0-test-router-tls:
      entryPoints:
      - websecure
      rule: Host(`prometheus-k8s-operator-0.prometheus-k8s-operator-endpoints.test.svc.cluster.local`)
      service: juju-prometheus-k8s-0-test-service
      tls:
        domains:
        - main: 10.64.140.43
          sans:
          - '*.10.64.140.43'
  services:
    juju-prometheus-k8s-0-test-service:
      loadBalancer:
        servers:
        - url: http://prometheus-k8s-operator-0.prometheus-k8s-operator-endpoints.test.svc.cluster.local:8080
```

- ingress-per-app:
```
http:
  middlewares:
    juju-sidecar-noprefix-test-identity-platform-login-ui-operator:
      stripPrefix:
        forceSlash: false
        prefixes:
        - /test-identity-platform-login-ui-operator
  routers:
    juju-test-identity-platform-login-ui-operator-router:
      entryPoints:
      - web
      middlewares:
      - juju-sidecar-noprefix-test-identity-platform-login-ui-operator
      rule: PathPrefix(`/test-identity-platform-login-ui-operator`)
      service: juju-test-identity-platform-login-ui-operator-service
    juju-test-identity-platform-login-ui-operator-router-tls:
      entryPoints:
      - websecure
      rule: PathPrefix(`/test-identity-platform-login-ui-operator`)
      service: juju-test-identity-platform-login-ui-operator-service
      tls:
        domains:
        - main: 10.64.140.43
          sans:
          - '*.10.64.140.43'
  services:
    juju-test-identity-platform-login-ui-operator-service:
      loadBalancer:
        servers:
        - url: http://identity-platform-login-ui-operator-0.identity-platform-login-ui-operator-endpoints.test.svc.cluster.local:8080
```

### To Reproduce

1. `juju deploy traefik-route-k8s root_url=...`
2. `juju deploy traefik-k8s`
3. `juju deploy prometheus-k8s`
4. `juju relate traefik-route-k8s prometheus-k8s`
5. `juju relate traefik-route-k8s traefik-k8s`

### Environment

n/a

### Relevant log output

```shell
n/a
```
